# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='state',
            field=models.BooleanField(choices=[(0, '待做'), (1, '完成')], default=0, max_length=1),
        ),
    ]
